// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `headers/example.h`.
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Int8> transByte(
    ffi.Pointer<ffi.Int8> arg,
  ) {
    return _transByte(
      arg,
    );
  }

  late final _transByte_ptr =
      _lookup<ffi.NativeFunction<_c_transByte>>('transByte');
  late final _dart_transByte _transByte =
      _transByte_ptr.asFunction<_dart_transByte>();
}

typedef _c_transByte = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg,
);

typedef _dart_transByte = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> arg,
);
